### ISSUE TITLE
I'm getting some ts errors

### ISSUE THREAD

**Issue by travbus** [fyeeme/vite-quasar#1]
Is there a way to fix these errors? I'm just starting to learn about type script this is over my head. Thanks for making this template by the way its a big help!

<img width="1706" alt="Screen Shot 2022-02-12 at 3 03 29 PM" src="https://user-images.githubusercontent.com/18337819/153729946-3df7e984-73b9-44f9-a296-6814ad4cb1af.png">

**Comment by fyeeme** [comment]
So, did you solved?

**Comment by travbus** [comment]
Yes I just had to reboot editor haha, I must have added a dependency by accident. thanks for posting this it’s a great structure
