### ISSUE TITLE
Add SSR support

### ISSUE THREAD

**Issue by alizangiabadicode** [fyeeme/vite-quasar#2]
Hi
I'm using vitesse as my vue3 template. I added quasar vite plugin to it. problem is that no html is generated for quasar components when I build the project with vite-ssg.

**Comment by fyeeme** [comment]
ssg is not used in my project currently, but pr is welcome

**Comment by fyeeme** [comment]
@alizangiabadicode  as[official](https://quasar.dev/start/vite-plugin) says 
>Warning! Current limitation:
SSR builds with Quasar Vite plugin are not yet supported.

**Comment by fyeeme** [comment]
@alizangiabadicode  quasar has support ssr with [quasar-cli-with-vite](https://quasar.dev/quasar-cli-vite/convert-to-quasar-cli-with-vite),and you can try it
