### ISSUE TITLE
Error Unknown command "dev"

### ISSUE THREAD

**Issue by thefeymesaleng** [fyeeme/vite-quasar#4]
A brand new project created with `npm init quasar` throw `Error Unknown command "dev"` after use `quasar dev`

Operating System        Windows_NT(10.0.22000) - win32/x64
NodeJs                  16.13.1

Global packages    
  NPM                   8.3.1
  yarn                  Not installed
  @quasar/cli           1.2.2
  @quasar/icongenie     Not installed
  cordova               Not installed

**Comment by fyeeme** [comment]
close as this project is a out of box for use quasar with vite, if use want to init new project with quasar , got to offical for help
