### ISSUE TITLE
' Cannot access 'generatedRoutes' before initialization' when HMR activates on 'default.vue' 

### ISSUE THREAD

**Issue by ontwikkelfabriek** [fyeeme/vite-quasar#5]
It installs and runs without problems. But when you change any file ( e.g. default.vue) ,  that uses `generatedRoutes from 'virtual:generated-pages'`, the HMR will generate an error:

```
client.ts:28 ReferenceError: Cannot access 'generatedRoutes' before initialization
    at router.ts:5:47
warnFailedFetch @ client.ts:28
(anonymous) @ client.ts:333
await in (anonymous) (async)
fetchUpdate @ client.ts:320
(anonymous) @ client.ts:74
handleMessage @ client.ts:72
(anonymous) @ client.ts:45
client.ts:30 [hmr] Failed to reload /src/layouts/default.vue. This could be due to syntax errors or importing non-existent modules. (see errors above)
warnFailedFetch @ client.ts:30
(anonymous) @ client.ts:333
await in (anonymous) (async)
fetchUpdate @ client.ts:320
(anonymous) @ client.ts:74
handleMessage @ client.ts:72
(anonymous) @ client.ts:45
default.vue:33 Uncaught (in promise) TypeError: Cannot destructure property 'default' of 'undefined' as it is undefined.
    at default.vue:33:36
    at client.ts:424:52
    at client.ts:340:7
    at client.ts:195:57
    at Array.forEach (<anonymous>)
    at queueUpdate (client.ts:195:35)
```

**Comment by fyeeme** [comment]
Seams ok when update src/layout/default.vue, more system info need
<img width="595" alt="image" src="https://user-images.githubusercontent.com/6078758/165213185-f2a14110-76fa-4d97-9fa7-b7aba1941f06.png">

**Comment by fyeeme** [comment]
@ontwikkelfabriek , I'v push a new commit, and you can have a try.

**Comment by ontwikkelfabriek** [comment]
@fyeeme 

I cloned and rebuild the app from your updated source, but same error.  What system info would you like? 

some other things that are weird:

1. Quasar cli `quasar info` command is not working for this project.( does not recognize the folder as a quasar project, not a good sign).  Other projects work just fine with quasar info btw
2. the **quasar.conf.js** file missing for this project.

**Comment by fyeeme** [comment]
<img width="274" alt="image" src="https://user-images.githubusercontent.com/6078758/166100770-433cad9b-9641-4d3b-acb8-6662cc57cca6.png">

quasar has quasar cli and quasar vite plugin 

and this project is a vite plugin base with windycss and other libs out of box for use.

if you want to use Quasar cli , you should go to [official website ](https://quasar.dev/start/quasar-cli) for more detail.

and  default layout is just  for listing all of the simple demo include quasar compent and windycss, you can delete or edit for free.
