### ISSUE TITLE
strange error when installing template

### ISSUE THREAD

**Issue by Galllarate** [fyeeme/vite-quasar#9]
When I install the template and execute essentially two commands
npm install 
npm run dev

I get such an error

![image](https://user-images.githubusercontent.com/47278133/194912857-b977f1fb-ed56-4499-babb-9edcef6a3567.png)

**Comment by vitjaz** [comment]
> When I install the template and execute essentially two commands npm install npm run dev
> 
> I get such an error
> 
> ![image](https://user-images.githubusercontent.com/47278133/194912857-b977f1fb-ed56-4499-babb-9edcef6a3567.png)

Have you tried pnpm?

**Comment by fyeeme** [comment]
we you pnpm. may you have a try on pnpm

**Comment by vitjaz** [comment]
> we you pnpm. may you have a try on pnpm

**npm works fine. only proxy errors.**
![image](https://user-images.githubusercontent.com/47814045/205861379-9d5e1ae5-7b0f-45f5-b453-b138b49d9810.png)

**pnpm works fine also.**
![image](https://user-images.githubusercontent.com/47814045/205863148-d1bcc22e-98b7-470f-830b-e6c4251249b9.png)

my versions:
![image](https://user-images.githubusercontent.com/47814045/205863861-21d30f13-d9b9-4714-a008-05ac6503652c.png)

**Comment by fyeeme** [comment]
proxy ip and port address should be your own server. api address.
